vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /public/pages/images
            upload_destination: '%kernel.project_dir%/public/pages/images'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        article_couverture:
            uri_prefix: /upload/articles/couvertures
            upload_destination: '%kernel.project_dir%/public/upload/articles/couvertures'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
        article_miniature:
            uri_prefix: /upload/articles/miniatures
            upload_destination: '%kernel.project_dir%/public/upload/articles/miniatures'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
